IdaCustom/src/main/java/cl/itdchile/custom/model/RunningJobEntity.java
package cl.itdchile.custom.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "t_running_job")
public class RunningJobEntity extends BaseObject {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	protected int id;

	@Column(name = "thread_name", nullable = false)
	protected String thread_name;

	@Column(name = "id_job_type", nullable = false, insertable = false, updatable = false)
	protected int id_job_type;

	@Column(name = "id_process_type", nullable = false, insertable = false, updatable = false)
	protected int id_process_type;

	@Column(name = "created_at", nullable = false)
	protected Date created_at;

	@OneToOne
	@JoinColumn(name = "id_job_type")
	private JobTypeEntity jobType;

	@OneToOne
	@JoinColumn(name = "id_process_type")
	private ProcessTypeEntity processType;

	@Transient
	protected boolean isThreadActive;

	@Transient
	protected String executionTime;

	public RunningJobEntity() {
		super();
		// TODO Auto-generated constructor stub
	}

	public JobTypeEntity getJobType() {
		return jobType;
	}

	public void setJobType(JobTypeEntity jobType) {
		this.jobType = jobType;
	}

	public ProcessTypeEntity getProcessType() {
		return processType;
	}

	public void setProcessType(ProcessTypeEntity processType) {
		this.processType = processType;
	}

	public String getExecutionTime() {
		return executionTime;
	}

	public void setExecutionTime(String executionTime) {
		this.executionTime = executionTime;
	}

	public boolean isThreadActive() {
		return isThreadActive;
	}

	public void setThreadActive(boolean isThreadActive) {
		this.isThreadActive = isThreadActive;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getThread_name() {
		return thread_name;
	}

	public void setThread_name(String thread_name) {
		this.thread_name = thread_name;
	}

	public Date getCreated_at() {
		return created_at;
	}

	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}

//	public RunningJobEntity(String thread_name, int id_job_type, int id_process_type, Date created_at) {
//		super();
//		this.thread_name = thread_name;
//		this.id_job_type = id_job_type;
//		this.id_process_type = id_process_type;
//		this.created_at = created_at;
//	}

}

IdaCustom/src/main/java/cl/itdchile/custom/client/controller/ProcessesController.java
package cl.itdchile.custom.client.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import cl.itdchile.custom.EnumJobType;
import cl.itdchile.custom.dao.client.IProcessesManager;
import cl.itdchile.custom.model.RunningJobEntity;

@ManagedBean(name = "processesController")
@Controller
@ViewScoped
public class ProcessesController implements Serializable {

	private static Logger log = Logger.getLogger(ProcessesController.class);

	private FacesContext context = FacesContext.getCurrentInstance();

	@Autowired
	protected IProcessesManager manager;

	protected List<RunningJobEntity> oldProcessList;
	protected List<RunningJobEntity> filteredoldProcessList;

	@PostConstruct
	public void init() {
		try {
			log.info("Module: Processes" + EnumJobType.GENERATE_INPUT);
			this.getData();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	public void getData() {
		try {
			this.oldProcessList = this.manager.getOldProcesses();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	public void stopProcess(RunningJobEntity entity) {
		try {
			this.manager.stopProcess(entity);
			context.addMessage("growl", new FacesMessage(FacesMessage.SEVERITY_INFO, "Proceso Detenido", null));
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			context.addMessage("growl", new FacesMessage(FacesMessage.SEVERITY_FATAL, "Error", e.getMessage()));
		}
	}

	public void stopAllProcess() {
		try {
			this.manager.stopAllProcess(this.oldProcessList);
			context.addMessage("growl",
					new FacesMessage(FacesMessage.SEVERITY_INFO, "Todos los Procesos Detenidos", null));
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			context.addMessage("growl", new FacesMessage(FacesMessage.SEVERITY_FATAL, "Error", e.getMessage()));
		}
	}

	public void refresh() {

	}

	public List<RunningJobEntity> getOldProcessList() {
		return oldProcessList;
	}

	public void setOldProcessList(List<RunningJobEntity> oldProcessList) {
		this.oldProcessList = oldProcessList;
	}

	public List<RunningJobEntity> getFilteredoldProcessList() {
		return filteredoldProcessList;
	}

	public void setFilteredoldProcessList(List<RunningJobEntity> filteredoldProcessList) {
		this.filteredoldProcessList = filteredoldProcessList;
	}

}

IdaCustom/src/main/webapp/views/Admin/Modules/Processes/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/template.xhtml">

	<ui:define name="metadata">
		<ui:param name="title" value="Configuracion de Conexiones" />
	</ui:define>

	<ui:define name="content">

		<section class="content-header">
			<h1>Procesos</h1>
			<ol class="breadcrumb">
				<li><a href="#"> Procesos</a></li>
			</ol>

			<section class="content">

				<h:form prependId="false" id="formMain">
					<p:growl id="growl" showDetail="true" widgetVar="growl" />
					<p:poll interval="60" listener="#{processesController.getData}"
						update="growl tablePanel" onstart="PF('bui').show();"
						oncomplete="PF('bui').hide();" />
					<div class="row">

						<p:panel id="tablePanel" styleClass="ui-main-panel">
							<div class="row ui-main">
								<p:commandButton styleClass="ui-main-button-error "
									icon="far fa-stop-circle" immediate="true"
									value="Detener Todos"
									oncomplete="PF('dlg1').show();PF('bui').hide();"
									onstart="PF('bui').show();"
									action="#{processesController.stopAllProcess}"
									update="growl tablePanel">
								</p:commandButton>
							</div>
							<div class="row">
								<p:dataTable var="item"
									value="#{processesController.oldProcessList}" reflow="true"
									rows="25" id="tableList" widgetVar="tableList"
									rowsPerPageTemplate="25,50,75,100" rowIndexVar="rowNumber"
									paginator="true"
									filteredValue="#{processesController.filteredoldProcessList}"
									paginatorPosition="bottom" scrollable="false"
									currentPageReportTemplate="({currentPage} de {totalPages})"
									paginatorTemplate="{totalPages} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {Exporters}"
									styleClass="ui-main dataTable">

									<f:facet name="{totalPages}">
										<h:outputLabel
											value="Cantidad de Registros: #{processesController.oldProcessList.size()}"
											rendered="#{processesController.oldProcessList != null}"></h:outputLabel>
									</f:facet>

									<f:facet name="{Exporters}">
										<h:commandLink
											style="margin-right:15px;text-decoration:none;padding:2px;">
											<p:dataExporter type="pdf" target="tableConections"
												fileName="Consumo"></p:dataExporter>
											<p:graphicImage name="images/tables/iconopdfcolor2.png"
												style="width: 25px;" />
										</h:commandLink>
										<h:commandLink style="margin-right:15px;text-decoration:none;">
											<p:dataExporter type="xls" target="tableConections"
												fileName="Consumo"></p:dataExporter>
											<p:graphicImage name="images/tables/iconoexcelcolor2.png"
												style=" width: 25px;" />
										</h:commandLink>
									</f:facet>
									<p:column headerText="" width="100" styleClass="ui-col-center">
										<div
											class="col-sm-12 col-md-12 text-center ui-main-button-table-action">
											<p:commandLink title="Eliminar"
												oncomplete="PF('bui').hide();" onstart="PF('bui').show();"
												update="growl tablePanel"
												action="#{processesController.refresh}">
												<i class="far fa-stop-circle"></i>
												<p:confirm header="Confirmación"
													message="Desea eliminar el proceso?"
													icon="fas fa-question-circle" />
											</p:commandLink>
										</div>
									</p:column>

									<p:column headerText="Tipo" styleClass="ui-col-center">
										<h:outputText value="#{item.jobType.description}" />
									</p:column>

									<p:column headerText="Proceso" styleClass="ui-col-center">
										<h:outputText value="#{item.processType.name}" />
									</p:column>

									<p:column headerText="Iniciado En">
										<h:outputText value="#{item.created_at}">
											<f:convertDateTime pattern="dd/MM/yyyy HH:mm" locale="es_CL" />
										</h:outputText>
									</p:column>

									<p:column headerText="Tiempo de Ejecución"
										styleClass="ui-col-code">
										<h:outputText value="#{item.executionTime}" />
									</p:column>

									<p:column headerText="Hilo Activo" styleClass="ui-col-center">
										<h:outputLabel rendered="#{item.threadActive eq false}">
											<i class="fas fa-times"></i>
										</h:outputLabel>

										<h:outputLabel rendered="#{item.threadActive eq true}">
											<i class="fas fa-check"></i>
										</h:outputLabel>
									</p:column>

								</p:dataTable>
							</div>
						</p:panel>
					</div>
				</h:form>

			</section>

		</section>

	</ui:define>

</ui:composition>